### ISSUE TITLE
Feature to add custom websites to block

### ISSUE THREAD

**Issue by anonthedev** [pritipsingh/The-Productive-Champion#10]
Currently it only blocks only certain websites, there should be a feature that allows the users to choose which websites to block and also add new websites that they want to block.

**Comment by pritipsingh** [comment]
Hey @anonthedev thanks for the suggestion. Following the conversation off twitter - assigning this to you :)

**Comment by anonthedev** [comment]
yo @pritipsingh there's no manifest.json file in the repo?
