### ISSUE TITLE
Content script running again and again

### ISSUE THREAD

**Issue by Kabirsharma2607** [pritipsingh/The-Productive-Champion#16]
https://github.com/pritipsingh/The-Productive-Champion/assets/111571318/a1c374ef-902b-4aa7-b7bc-df89456ce952

I was working on the popup functionality but I witnessed that content script was running for more than 1 time causing the pop-up to occur again and again. There might be some issue with the background. Can anyone me help to figure it out?

**Comment by satyam4484** [comment]
As Per my observation, it is running because of the websites that we have mentioned in the content/index.ts which keeps checking everytime when some new things has been arrived.

**Comment by pritipsingh** [comment]
True, it loops around each website that's mentioned and when it finds it, it stops. It's not running again again

**Comment by satyam4484** [comment]
may be we can create a hashmap to check whether this website already checked or not if not then run else skip it
