### ISSUE TITLE
editWebsiteToBlock not opening

### ISSUE THREAD

**Issue by anshmourya** [pritipsingh/The-Productive-Champion#19]
##error demo
![issue](https://github.com/pritipsingh/The-Productive-Champion/assets/97006945/f5642288-0c4a-41b6-b3e9-bde0a2e2faf8)

editWebsiteToBlock is not opening due to the "websiteToBlock" data stored in the local storage.  have checked the entire codebase but have not found any localstorage.setitem('websiteToBlock')

**Comment by pritipsingh** [comment]
Hey @anshmourya Do you mind pulling all the changes once from the main and trying again?  local storage is in the component folder


https://github.com/pritipsingh/The-Productive-Champion/blob/main/my-extension/src/components/WebsiteEditPage.tsx


<img width="925" alt="Screenshot 2024-01-26 at 3 22 55 PM" src="https://github.com/pritipsingh/The-Productive-Champion/assets/85965351/1c0bb99f-920d-4548-b74a-5cece20acbd8">

**Comment by ChinmayMhatre** [comment]
Hey , I was facing the same issue.
On line 20 
https://github.com/pritipsingh/The-Productive-Champion/blob/main/my-extension/src/components/WebsiteEditPage.tsx

`    let data = [...customWebsites, ...alreadyBlockedWebsites]
`

This causes an issue if `customWebsites` is `null` which is true initially, thus it cannot iterator over null and breaks the page.
The solution I found is to check if it is null. 

`let data = customWebsites ? [...customWebsites, ...alreadyBlockedWebsites] : [...alreadyBlockedWebsites];
`

<img width="1193" alt="image" src="https://github.com/pritipsingh/The-Productive-Champion/assets/51131670/2bba9a96-ed39-421d-a3d5-c7c02e307671">

**Comment by pritipsingh** [comment]
Thanks @ChinmayMhatre Do you mind making a PR for it?
