### ISSUE TITLE
Make the already existing websites customizable.

### ISSUE THREAD

**Issue by pritipsingh** [pritipsingh/The-Productive-Champion#23]
<img width="334" alt="Screenshot 2024-02-01 at 9 28 59 PM" src="https://github.com/pritipsingh/The-Productive-Champion/assets/85965351/8c42d44a-df60-422b-97ab-5978d205e6f3">

We currently have a bunch of websites that are blocked, maybe we can make it customizable

**Comment by code-withAshish** [comment]
> We currently have a bunch of websites that are blocked, maybe we can make it customizable

can you explain more on this? what exactly does `customizable` mean?

**Comment by pritipsingh** [comment]
There are websites that are already blocked and then you've the option to add any website you might wanna block that are not already there as default. So now we want to make default websites customizable too as in- have the option to remove them as well

**Comment by ahsanfarooq210** [comment]
Hi @pritipsingh. Is there anyone working on this issue because I would like to work on this one.

**Comment by pritipsingh** [comment]
hI @ahsanfarooq210 This is already implemented. Maybe we can brainstrom on bringing ADHD mode to live
