### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by pritipsingh** [pritipsingh/The-Productive-Champion#3]
Remove all the console logs, shift each part of the `App.tsx` to a file `Components/[name].tsx`

I have properly commented it for example: 
<img width="547" alt="Screenshot 2023-12-31 at 11 25 27 PM" src="https://github.com/pritipsingh/The-Productive-Champion/assets/85965351/8c24d687-d673-4c5d-9f21-007e09ec65c6">
They all look cluttered in one page `app.tsx` so having a component based folder structure will help a lpt

**Comment by Ydixit007** [comment]
Opened a pull request solving this issue #12
