### ISSUE TITLE
Design the injected page during focus hours

### ISSUE THREAD

**Issue by pritipsingh** [pritipsingh/The-Productive-Champion#4]
It currently looks like this:
<img width="1359" alt="Screenshot 2023-12-31 at 11 27 10 PM" src="https://github.com/pritipsingh/The-Productive-Champion/assets/85965351/a9f2f250-91b8-4106-b1bc-00c7ba430ba0">

I want to make it look more aesthetic like the popup

**Comment by Kabirsharma2607** [comment]
Hey Pritip, You can assign this to me.

**Comment by Kabirsharma2607** [comment]
Hey Priti I can work on this.  Could you please assign this issue to me?

**Comment by pritipsingh** [comment]
done @Kabirsharma2607

**Comment by anshmourya** [comment]
"If the task is still pending, I'd like to take over and complete it."

**Comment by pritipsingh** [comment]
Hey @anshmourya sorry I missed this message. Sure go ahead! Assigning this to you
