### ISSUE TITLE
Change Font to Inter

### ISSUE THREAD

**Issue by pritipsingh** [pritipsingh/The-Productive-Champion#7]
I don't like the current font, Inter is nice and classy

**Comment by Abhinavcode13** [comment]
I can know the font folder directory @pritipsingh .

**Comment by pritipsingh** [comment]
Hey there is no folder for it. We can leverage `tailwind config` or the global css file` index.css`

**Comment by Varun270** [comment]
<img width="396" alt="build" src="https://github.com/pritipsingh/The-Productive-Champion/assets/75975268/7c1dbdc4-1bad-4c0e-9388-bdabfb28ed04">

@pritipsingh  Hi, I am trying to load the folder containing the extension file and I am getting this error. How can I fix this?

**Comment by pritipsingh** [comment]
Hey @Varun270 make sure you're loading the `build `folder inside my-extension after you've run: `yarn build` . Also make sure to do- `yarn install` inside my-extension

**Comment by Varun270** [comment]
<img width="791" alt="la" src="https://github.com/pritipsingh/The-Productive-Champion/assets/75975268/88fd5a83-ae0d-4bca-8581-eb19ad609cc0">
<img width="292" alt="la1" src="https://github.com/pritipsingh/The-Productive-Champion/assets/75975268/be405225-1441-4901-9b66-51860191cf6b">

I followed the same process as you mentioned still am not able to load the build folder!!

**Comment by pritipsingh** [comment]
can you send me the pic of the build folder? Does it look like this? 
<img width="190" alt="Screenshot 2024-01-04 at 12 39 23 PM" src="https://github.com/pritipsingh/The-Productive-Champion/assets/85965351/3e7ce5bc-440f-4a0e-ad2b-49b09b1266f4">

**Comment by Varun270** [comment]
Sure , Here it is - 

<img width="293" alt="LL" src="https://github.com/pritipsingh/The-Productive-Champion/assets/75975268/0964ddd4-548c-40a5-939f-00a7093d3e6f">

**Comment by pritipsingh** [comment]
Yep it doesn't have background file. I think you did yarn build before changing directory to my-extension. Do you mind deleting the whole build file first. 
cd to my-extension and then do yarn build?

**Comment by Varun270** [comment]
Okay Will do!

**Comment by Ydixit007** [comment]
Hey @Varun270 , make sure you change the build script in package.json to "build": "set INLINE_RUNTIME_CHUNK=false && react-app-rewired build", if you are using a windows machine. I too faced the same issue, the above script fixed it.

**Comment by Varun270** [comment]
@Ydixit007 I did what you suggested and then again did yarn build and tried loading the build folder but still got the same error! Also, as suggested by @pritipsingh, I deleted the build folder, did cd my-extension, and then did the yarn build again. Still, the problem persists.

**Comment by psankhe28** [comment]
Hi @pritipsingh , I have created a pr request for this issue. Please have a look. [Link](https://github.com/pritipsingh/The-Productive-Champion/pull/25)
